### ISSUE TITLE
cannot open include file 'afxres.h'

### ISSUE THREAD

**Issue by MLXProjects** [m417z/winspy#5]
Hello, I'm having the title's problem after trying to compile the code on VS 2019. The file "afxres.h" is included by winspy.rc at line 10, looks like it should be made by VS but it isn't. 
What can I do?

**Comment by m417z** [comment]
You can solve the compilation error by installing MFC and ATL support.
See the answer here:
https://social.msdn.microsoft.com/Forums/en-US/6b69607a-8a84-4e46-b3c8-5cd832bfb9c7/vs-2017-rc-file-error-rc1015-cannot-open-include-file-afxresh?forum=vcgeneral

It's probably possible to get rid of this dependency. Pull requests are welcome :)

**Comment by MLXProjects** [comment]
Solved, that was pretty stupid of my part. Thanks!
